### ISSUE TITLE
How to use this Zend plugin with the skeleton app?

### ISSUE THREAD

**Issue by geertijewski** [eth8505/zf-symfony-console#3]
In the skeleton app the `public/index.php` does not return an instance of Zend\Mvc\Application.
```php
#!/usr/bin/env php
<?php

/* ... omitted for brevity ... */

// Run the application!
Application::init($appConfig)->run();
```

What would need to be changed to use it with this zend module?

**Comment by eth8505** [comment]
Hi @geertijewski . Apologies for not getting back to you sooner, I simply wasn't anywhere close to a computer. I haven't actually used the module with the skeleton application myself, but since I based the module on RDN Console, you might try what is suggested there: https://github.com/radnan/rdn-console#how-to-use

Simply return your application from your index.php.

**Comment by geertijewski** [comment]
Ah sure. I was thinking that `Applcation::run()` does not return so it simply did not occur to me that I could call run and then return.

Thank you very much
